version: '3.8'

services:
  # Frontend development
  frontend-dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - mincommerce-network

  # Frontend production
  frontend-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - mincommerce-network

  # Backend service (assuming it exists)
  backend:
    image: mincommerce-rest:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/mincommerce
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - mincommerce-network

  # Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mincommerce
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mincommerce-network

  # Redis
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - mincommerce-network

volumes:
  postgres_data:
  redis_data:

networks:
  mincommerce-network:
    driver: bridge
